version: "3"

services:
  app:
    image: graphite-test:latest
    stdin_open: true
    tty: true
    build: .
    # command: xhost +local:docker 
    command: GraphiteThree/build/Linux64-gcc-dynamic-Release/bin/graphite
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:rw
      - ~/:/mydisk
      
    network_mode: host
